package Modelos;
// Generated 18-nov-2020 18:07:36 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * FacturasLin generated by hbm2java
 */
public class FacturasLin  implements java.io.Serializable {


     private FacturasLinId id;
     private Articulos articulos;
     private FacturasCab facturasCab;
     private BigDecimal cantidad;
     private BigDecimal precio;
     private BigDecimal dtolinea;
     private BigDecimal ivalinea;

    public FacturasLin() {
    }
    
    public FacturasLin(FacturasLinId id, Articulos articulos, FacturasCab facturasCab, BigDecimal cantidad, BigDecimal precio, BigDecimal dtolinea, BigDecimal ivalinea) {
       this.id = id;
       this.articulos = articulos;
       this.facturasCab = facturasCab;
       this.cantidad = cantidad;
       this.precio = precio;
       this.dtolinea = dtolinea;
       this.ivalinea = ivalinea;
    }
    
    public FacturasLinId getId() {
        return this.id;
    }
    
    public void setId(FacturasLinId id) {
        this.id = id;
    }
    public Articulos getArticulos() {
        return this.articulos;
    }
    
    public void setArticulos(Articulos articulos) {
        this.articulos = articulos;
    }
    public FacturasCab getFacturasCab() {
        return this.facturasCab;
    }
    
    public void setFacturasCab(FacturasCab facturasCab) {
        this.facturasCab = facturasCab;
    }
    public BigDecimal getCantidad() {
        return this.cantidad;
    }
    public BigDecimal getFormattedCantidad(String valor) {
        Long l = Long.valueOf(valor);
        return cantidad.valueOf(l);
    }
    
    public void setCantidad(BigDecimal cantidad) {
        this.cantidad = cantidad;
    }
    public BigDecimal getPrecio() {
        return this.precio;
    }
    public BigDecimal getFormattedPrecio(String valor) {
        Long l = Long.valueOf(valor);
        return precio.valueOf(l);
    }
    
    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }
    public BigDecimal getDtolinea() {
        return this.dtolinea;
    }
    public BigDecimal getFormattedDto(String valor) {
        Long l = Long.valueOf(valor);
        return dtolinea.valueOf(l);
    }
    
    public void setDtolinea(BigDecimal dtolinea) {
        this.dtolinea = dtolinea;
    }
    public BigDecimal getIvalinea() {
        return this.ivalinea;
    }
    public BigDecimal getFormattedIvaLinea(String valor) {
        Long l = Long.valueOf(valor);
        return ivalinea.valueOf(l);
    }
    
    public void setIvalinea(BigDecimal ivalinea) {
        this.ivalinea = ivalinea;
    }




}


